### ISSUE TITLE
wait, is this working via cloud only?

### ISSUE THREAD

**Issue by elektrinis** [patrickhilker/tedee_hass_integration#38]
I am looking for a lock that will work directly with HA, without cloud and without internet access. Preferrably zigbee, alternatively bt mesh, worst case z-wave. No wifi please.

From description I don't really get the idea. Does this need internet access to work?

**Comment by vytautasgimbutas** [comment]
Taip. Yes.

**Comment by bzumik1** [comment]
You can use this lock trough Home Kit integration than it is fully local (connected directly by bluetooth to HA server or with ESPHome bluetooth proxy). You will lose some functionality though.

Also there is plan that bridge should support fully local API, about 3 months ago there was info that it will be released soon but if I am right, it has not been released yet, so we are stuck with the cloud dependent API for now.

**Comment by elektrinis** [comment]
If I had a bridge for every brand of devices I use, I had like 20 bridges :D Yet I still have no bridges, "zaro", as per Polish meme.
This lock has great potential, but it seems it falls in to "maybe some day" category for now, like many others.
So far the only one I found to work locally and fit my uPVC door is Connexis L1, but it's z-wave.

**Comment by bzumik1** [comment]
I understand, but as I said you can use it without bridge connected directly to HA server via bluetooth.

**Comment by elektrinis** [comment]
Oh, I misunderstood that part.
What functions do I get, and what I lose in this case?

**Comment by bzumik1** [comment]
I am using it in two locations: one with a bridge and one connected directly to HA. (Actually, I use ESPHome Bluetooth proxy because my HA server is located far from the lock.) So far, I have encountered two 'complications.' One is that the setup is a bit complicated (but you only do it once...). The second one is that if you set up the lock to automatically retract the spring, then when you press 'unlock' from HA, it will always open the door, not just unlock it. With the bridge, you can unlock the door when you're closer to home and then open it when you're right next to the door, making it slightly faster (you don't have to wait in front of the door for the unlock, so it's 0.5 - 1 second faster). The second issue is only a problem when you don't have a handle on the outside of your door.

**Comment by elektrinis** [comment]
Hm, retracting the spring is actually not a problem in my case, as I don't need it.
I will however have a problem with one of my doors which is "lift to lock", and the key can't be turned until you lift the handle manually. Will need to think of a way to detect that to not jam anything.

So far it actually sounds to be usable without a hub. Thank you.
