### ISSUE TITLE
Lock status change updates not always are result of real state change

### ISSUE THREAD

**Issue by pkordal** [patrickhilker/tedee_hass_integration#7]
Hi!

I am struggling a bit with this great plugin. All works great, except strange behavior happening 2-3 times a day. It is worth noting that I am using HA HomeKit integration which makes the lock added to HA with this plugin to be accessible in the Apple ecosystem. 

The error described below makes HomeKit integration of the lock initiate a fake “lock closed” event which happens without the preceding “lock open” event. I am guessing this “lock closed” is being sent once the state is retrieved again with a successful API request, which happened right after failing one. 
It makes HomeKit to send push notifications on lock being closed, even though it hasn’t been open before, what is a bit frustrating for family members. Also some automations around lock state do behave quite randomly because of it.

Thank you for taking a look at it.

`
Logger: homeassistant.helpers.entity
Source: custom_components/tedee/lock.py:123 
Integration: Tedee (documentation, issues) 
First occurred: 09:58:57 (1 occurrences) 
Last logged: 09:58:57

Update for lock.doorlock fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 739, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tedee/lock.py", line 123, in update
    self._available = self._client.update(self._lock.get_id())
  File "/usr/local/lib/python3.10/site-packages/pytedee/TedeeClient.py", line 181, in update
    self.get_state()
  File "/usr/local/lib/python3.10/site-packages/pytedee/TedeeClient.py", line 153, in get_state
    states = r.json()["result"]
KeyError: 'result'
`

**Comment by pkordal** [comment]
I took a closer look and I was wrong in suggesting this error from the log has anything to do with described behavior. Please see what the log looks like, nevertheless, I see no more connection with the error log. 

<img width="297" alt="Zrzut ekranu 2023-03-05 o 18 15 52 png" src="https://user-images.githubusercontent.com/3457792/222975530-adbe7f98-8e56-44a2-96fa-eeb76b86ceea.png">

**Comment by rsporsche** [comment]
So the issue is that automations are being triggered by the transition from 'unavailable' to 'locked'? 

I had a similar issue where I was using a 'Device' trigger and solved by changing to a State trigger explicitly for the transition from 'Unlocked' to 'Locked' state.

I had some trouble configuring the automation though because I would select "Locked" or "Unlocked" in the GUI but it didn't trigger as expected. I noticed when I saved then re-opened the automation then sometimes one or the other would have changed to "on" or "off" and then editing the yaml to use "on" and "off" instead of "Unlocked" and "Locked" made it work. Very odd but I think nothing to do with this integration.
